### ISSUE TITLE
Error registering model pipeline

### ISSUE THREAD

**Issue by christoth** [sassoftware/python-sasctl#21]
I’m trying to register a model pipeline with sasctl (register_model) and ran into the following warning and error (last line of stack trace).

I am able to serialize it to disk with pickle. 

Thanks

`# Import and prepare data

hmeq = pd.read_csv('data/hmeq.csv')
print(hmeq.head())

print(hmeq.shape)

# Get y values
y = hmeq.pop('BAD').values

print(hmeq.dtypes)

# Get data types for X values
kinds = np.array([dt.kind for dt in hmeq.dtypes])
print(kinds)

# Select category columns
all_columns = hmeq.columns.values
is_cat = kinds == 'O'
cat_cols = all_columns[is_cat]
print(cat_cols)

# Train ML pipeline

# Create an ML pipeline that imputes and one-hot encodes category columns then trains an xgboost model
cat_si_step = ('si', SimpleImputer(strategy='constant', fill_value='MISSING'))
cat_ohe_step = ('ohe', OneHotEncoder(sparse=False, handle_unknown='ignore'))
cat_steps = [cat_si_step, cat_ohe_step]
cat_pipe = Pipeline(cat_steps)
cat_transformers = [('cat', cat_pipe, cat_cols)]
ct = ColumnTransformer(transformers=cat_transformers)
ml_pipe = Pipeline([('transform', ct), ('xgb', xgb.XGBClassifier())])
print(ml_pipe.fit(hmeq, y))

# score a record
print(ml_pipe.score(hmeq, y))

# save the model to disk
filename = 'hmeq-xgb.pkl'
pickle.dump(ml_pipe, open(filename, 'wb'))

# Register model in SAS

# Disables validation of SSL certificates to permit self-signed certs used in demo image
os.environ["SSLREQCERT"] = "no"

# Establish a session with Viya
with Session('sasserver.demo.sas.com', 'sasdemo', 'Orion123'):
    model_name = 'HMEQ-XGB'

    # Register the model in Model Manager
    mm_model = register_model(ml_pipe,
                   model_name,
                   input=hmeq,         # Use X to determine model inputs
                   project='HMEQ Demo',  # Register in "HMEQ Demo" project
                   force=True)      # Create project if it doesn't exist

    # Publish the model to the real-time scoring engine
    module = publish_model(mm_model['id'], 'maslocal')

    # Select the first row of training data
    x = hmeq.iloc[0, :]

    # Call the published module and score the record
    result = module.score(**x)
    print(result)`

C:\Dev\Util\Python37\lib\site-packages\sasctl\tasks.py:173: UserWarning: Unable to determine input/output variables.  Model variables will not be specified.
  warnings.warn('Unable to determine input/output variables. '
Traceback (most recent call last):
 File "c:\Users\chtoth\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\chtoth\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\chtoth\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Dev\Util\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Dev\Util\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Dev\Util\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\chtoth\OneDrive - SAS\Dev\python\model-mgmt\demo-hmeq.py", line 66, in <module>
    force=True)      # Create project if it doesn't exist
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\tasks.py", line 192, in register_model
    model = mr.create_model(model, project)
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\_services\model_repository.py", line 220, in create_model
    'Content-Type': 'application/vnd.sas.models.model+json'})
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\_services\service.py", line 123, in post
    return cls.request('post', *args, **kwargs)
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\_services\service.py", line 83, in request
    response = session.request(verb, path, **kwargs)
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\core.py", line 395, in request
    cert, json)
  File "C:\Dev\Util\Python37\lib\site-packages\requests\sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "C:\Dev\Util\Python37\lib\site-packages\requests\sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Dev\Util\Python37\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "C:\Dev\Util\Python37\lib\site-packages\requests\models.py", line 466, in prepare_body
    body = complexjson.dumps(json)
  File "C:\Dev\Util\Python37\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Dev\Util\Python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Dev\Util\Python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Dev\Util\Python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ColumnTransformer is not JSON serializable

**Comment by jlwalke2** [comment]
Fixed in commit 8325ba7389339a8c287c062b29ba452aa1dee7eb

**Comment by jlwalke2** [comment]
Merged to master by #24

**Comment by christoth** [comment]
Using v1.1.3, the pickle file is now imported! 

But variables are not created for either the model or the project and no DS2 code file are generated.

Thanks

These are the warning & error messages I get:

C:\Dev\Util\Python37\lib\site-packages\sasctl\tasks.py:189: UserWarning: Unable to determine input/output variables.  Model variables will not be specified.
  warnings.warn('Unable to determine input/output variables. '
Traceback (most recent call last):
  File "c:\Users\chtoth\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "c:\Users\chtoth\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\lib\python\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\chtoth\.vscode\extensions\ms-python.python-2019.8.29288\pythonFiles\lib\python\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Dev\Util\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Dev\Util\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Dev\Util\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\chtoth\OneDrive - SAS\Dev\python\model-mgmt\demo-hmeq.py", line 75, in <module>
    module = publish_model(mm_model['id'], 'maslocal')
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\tasks.py", line 290, in publish_model
    job = submit_request()
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\tasks.py", line 278, in submit_request
    force=replace)
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\_services\model_management.py", line 88, in publish_model
    'application/vnd.sas.models.publishing.request.asynchronous+json'})
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\_services\service.py", line 123, in post
    return cls.request('post', *args, **kwargs)
  File "C:\Dev\Util\Python37\lib\site-packages\sasctl\_services\service.py", line 87, in request
    response.text, response.headers, None)
urllib.error.HTTPError: HTTP Error 404: {"errorCode":0,"message":"The score code for the model could not be found.","details":["correlator: f740e0a4-a7c0-4b73-af9b-ba8eb72147c3","traceId: b180d631e1e9347d","path: /modelManagement/publish"],"links":[],"version":2,"httpStatusCode":404}

`import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import xgboost as xgb
import pickle

import os
from sasctl import Session, register_model, publish_model


# Import and prepare data

hmeq = pd.read_csv('data/hmeq.csv')
print(hmeq.head())

print(hmeq.shape)

# Get y values
y = hmeq.pop('BAD').values

print(hmeq.dtypes)

# Get data types for X values
kinds = np.array([dt.kind for dt in hmeq.dtypes])
print(kinds)

# Select category columns
all_columns = hmeq.columns.values
is_cat = kinds == 'O'
cat_cols = all_columns[is_cat]
print(cat_cols)


# Train ML pipeline

# Create an ML pipeline that imputes and one-hot encodes category columns then trains an xgboost model
cat_si_step = ('si', SimpleImputer(strategy='constant', fill_value='MISSING'))
cat_ohe_step = ('ohe', OneHotEncoder(sparse=False, handle_unknown='ignore'))
cat_steps = [cat_si_step, cat_ohe_step]
cat_pipe = Pipeline(cat_steps)
cat_transformers = [('cat', cat_pipe, cat_cols)]
ct = ColumnTransformer(transformers=cat_transformers)
ml_pipe = Pipeline([('transform', ct), ('xgb', xgb.XGBClassifier())])
print(ml_pipe.fit(hmeq, y))

# score a record
print(ml_pipe.score(hmeq, y))

# save the model to disk
filename = 'hmeq-xgb.pkl'
pickle.dump(ml_pipe, open(filename, 'wb'))


# Register model in SAS

# Disables validation of SSL certificates to permit self-signed certs used in demo image
os.environ["SSLREQCERT"] = "no"

# Establish a session with Viya
with Session('sasserver.demo.sas.com', 'sasdemo', 'Orion123'):
    model_name = 'HMEQ-XGB'

    # Register the model in Model Manager
    mm_model = register_model(ml_pipe,
                   model_name,
                   input=hmeq,         # Use X to determine model inputs
                   project='HMEQ-Py',  # Register in "HMEQ Demo" project
                   force=True)      # Create project if it doesn't exist

    # Publish the model to the real-time scoring engine
    module = publish_model(mm_model['id'], 'maslocal')

    # Select the first row of training data
    x = hmeq.iloc[0, :]

    # Call the published module and score the record
    result = module.score(**x)
    print(result)`

**Comment by jlwalke2** [comment]
The issue seems to be related to the Pipeline.

The `register_model` task attempts to use the provided model and `.predict()` the model outputs using the first row of the `input` data set.  If this process fails then a DS2 wrapper cannot be generated.  The task will still register the model, but score code can't be automatically generated and therefore the model can't be published (until corrected).

Attempting to register your pipeline generates the following exception inside sasctl:
```
Traceback (most recent call last):
  File "/Users/jozwal/GitHub/python-sasctl/src/sasctl/tasks.py", line 210, in register_model
    input_types=input, array_input=True)
  File "/Users/jozwal/GitHub/python-sasctl/src/sasctl/utils/pymas/core.py", line 247, in from_pickle
    return_message, code)
  File "/Users/jozwal/GitHub/python-sasctl/src/sasctl/utils/pymas/core.py", line 274, in _build_pymas
    output = target_func(input_types.iloc[0, :].values.reshape((1, -1)))
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 116, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/sklearn/pipeline.py", line 421, in predict
    Xt = transform.transform(Xt)
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/sklearn/compose/_column_transformer.py", line 539, in transform
    Xs = self._fit_transform(X, None, _transform_one, fitted=True)
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/sklearn/compose/_column_transformer.py", line 420, in _fit_transform
    self._iter(fitted=fitted, replace_strings=True), 1))
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/joblib/parallel.py", line 754, in dispatch_one_batch
    self._pickle_cache)
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/joblib/parallel.py", line 210, in __init__
    self.items = list(iterator_slice)
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/sklearn/compose/_column_transformer.py", line 419, in <genexpr>
    for idx, (name, trans, column, weight) in enumerate(
  File "/Users/jozwal/python-sasctl/lib/python3.6/site-packages/sklearn/compose/_column_transformer.py", line 657, in _get_column
    raise ValueError("Specifying the columns using strings is only "
ValueError: Specifying the columns using strings is only supported for pandas DataFrames
```

sasctl catches this and instead of failing, prints a warning and continues on with the registration process:
```
/Users/jozwal/GitHub/python-sasctl/src/sasctl/tasks.py:233: UserWarning: Unable to determine input/output variables.  Model variables will not be specified.
```

I'm not familiar enough with sklearn pipelines at this point to debug the issue, but essentially, sasctl is trying to run the following:
```
ml_pipe.predict(X.iloc[0, :].values.reshape((1, -1)))
```

If you can research why sklearn generates a ValueError from the line above, I should be able to tweak sasctl to be more pipeline-friendly.

I will also update the wording of the warning to indicate that other model features won't be available if variable input/outputs can't be determined.
